const menu = [
    {
      id: 1,
      title: 'Chicken Fried Rice',
      category: 'lunch',
      price: 90,
      img: './images/item-2.png',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'Chicken Biryani',
      category: 'lunch',
      price: 13.99,
      img: './images/item-1.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'ButterScotch',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'Idly',
      category: 'breakfast',
      price: '',
      img: './images/item-4.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'Chicken Sandwich',
      category: 'lunch',
      price: 50,
      img: './images/item-5.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'Ghee Roast',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'Sambar Rice',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.webp',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'Black Currant',
      category: 'shakes',
      price: 16.99,
      img: './images/item-9.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;